
spring:
  thymeleaf:
    cache: false
  application:
    name: nazi-shopping
  rabbitmq:
    host: ip
    port: 5672
    username: hjg
    password: hjg
    virtual-host: /ems
management:
  endpoints:
    web:
      exposure:
        include: '*'